# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),debug32)
  OBJDIR     = obj/x32/Debug/Irrlicht
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/libIrrlicht.a
  DEFINES   += -DDEBUG -D_IRR_STATIC_LIB_
  INCLUDES  += -I../../external/irrlicht/include -I../../external/irrlicht/source/aesGladman -I../../external/irrlicht/source/jpeglib -I../../external/irrlicht/source/libpng -I../../external/irrlicht/source/bzip2 -I../../external/irrlicht/source/lzma -I../../external/irrlicht/source/zlib
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m32 -L/usr/lib32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += -lglut
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR     = obj/x32/Release/Irrlicht
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/libIrrlicht.a
  DEFINES   += -DNDEBUG -D_IRR_STATIC_LIB_
  INCLUDES  += -I../../external/irrlicht/include -I../../external/irrlicht/source/aesGladman -I../../external/irrlicht/source/jpeglib -I../../external/irrlicht/source/libpng -I../../external/irrlicht/source/bzip2 -I../../external/irrlicht/source/lzma -I../../external/irrlicht/source/zlib
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -m32 -L/usr/lib32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += -lglut
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/Irrlicht
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/libIrrlicht.a
  DEFINES   += -DDEBUG -D_IRR_STATIC_LIB_
  INCLUDES  += -I../../external/irrlicht/include -I../../external/irrlicht/source/aesGladman -I../../external/irrlicht/source/jpeglib -I../../external/irrlicht/source/libpng -I../../external/irrlicht/source/bzip2 -I../../external/irrlicht/source/lzma -I../../external/irrlicht/source/zlib
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m64 -L/usr/lib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += -lglut
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/Irrlicht
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/libIrrlicht.a
  DEFINES   += -DNDEBUG -D_IRR_STATIC_LIB_
  INCLUDES  += -I../../external/irrlicht/include -I../../external/irrlicht/source/aesGladman -I../../external/irrlicht/source/jpeglib -I../../external/irrlicht/source/libpng -I../../external/irrlicht/source/bzip2 -I../../external/irrlicht/source/lzma -I../../external/irrlicht/source/zlib
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -m64 -L/usr/lib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += -lglut
  LDDEPS    += 
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/CSoftwareTexture2.o \
	$(OBJDIR)/CColorConverter.o \
	$(OBJDIR)/CIrrDeviceStub.o \
	$(OBJDIR)/CD3D9ParallaxMapRenderer.o \
	$(OBJDIR)/CIrrDeviceFB.o \
	$(OBJDIR)/CParticleAttractionAffector.o \
	$(OBJDIR)/CParticleRingEmitter.o \
	$(OBJDIR)/CImageWriterJPG.o \
	$(OBJDIR)/CAnimatedMeshMD3.o \
	$(OBJDIR)/CImageLoaderWAL.o \
	$(OBJDIR)/CTextSceneNode.o \
	$(OBJDIR)/CParticlePointEmitter.o \
	$(OBJDIR)/CIrrDeviceWinCE.o \
	$(OBJDIR)/COpenGLParallaxMapRenderer.o \
	$(OBJDIR)/CGUIColorSelectDialog.o \
	$(OBJDIR)/CPakReader.o \
	$(OBJDIR)/CParticleMeshEmitter.o \
	$(OBJDIR)/CZipReader.o \
	$(OBJDIR)/CAnimatedMeshHalfLife.o \
	$(OBJDIR)/CImageLoaderPNG.o \
	$(OBJDIR)/CGUIEditBox.o \
	$(OBJDIR)/CParticleRotationAffector.o \
	$(OBJDIR)/CReadFile.o \
	$(OBJDIR)/CGUIButton.o \
	$(OBJDIR)/CParticleCylinderEmitter.o \
	$(OBJDIR)/CBillboardSceneNode.o \
	$(OBJDIR)/CD3D8ShaderMaterialRenderer.o \
	$(OBJDIR)/CXMeshFileLoader.o \
	$(OBJDIR)/CMeshManipulator.o \
	$(OBJDIR)/CAnimatedMeshMD2.o \
	$(OBJDIR)/CTRGouraudAlphaNoZ2.o \
	$(OBJDIR)/CTRTextureLightMap2_M2.o \
	$(OBJDIR)/CD3D9CgMaterialRenderer.o \
	$(OBJDIR)/COpenGLNormalMapRenderer.o \
	$(OBJDIR)/CTRTextureFlat.o \
	$(OBJDIR)/CImageLoaderRGB.o \
	$(OBJDIR)/CTRGouraudWire.o \
	$(OBJDIR)/CTriangleSelector.o \
	$(OBJDIR)/CLMTSMeshFileLoader.o \
	$(OBJDIR)/CTRTextureLightMap2_M1.o \
	$(OBJDIR)/CParticleScaleAffector.o \
	$(OBJDIR)/CTriangleBBSelector.o \
	$(OBJDIR)/CTRTextureGouraudAdd.o \
	$(OBJDIR)/CPLYMeshFileLoader.o \
	$(OBJDIR)/COpenGLDriver.o \
	$(OBJDIR)/CGUIInOutFader.o \
	$(OBJDIR)/CWaterSurfaceSceneNode.o \
	$(OBJDIR)/CTRTextureGouraudNoZ2.o \
	$(OBJDIR)/CD3D9HLSLMaterialRenderer.o \
	$(OBJDIR)/CMetaTriangleSelector.o \
	$(OBJDIR)/CGUIEnvironment.o \
	$(OBJDIR)/CTRTextureGouraud2.o \
	$(OBJDIR)/CTerrainSceneNode.o \
	$(OBJDIR)/CGUIComboBox.o \
	$(OBJDIR)/CParticleGravityAffector.o \
	$(OBJDIR)/COBJMeshWriter.o \
	$(OBJDIR)/CDefaultSceneNodeAnimatorFactory.o \
	$(OBJDIR)/CD3D8Texture.o \
	$(OBJDIR)/CCameraSceneNode.o \
	$(OBJDIR)/CTRFlatWire.o \
	$(OBJDIR)/CGUISkin.o \
	$(OBJDIR)/CSphereSceneNode.o \
	$(OBJDIR)/CGUIMessageBox.o \
	$(OBJDIR)/CTRFlat.o \
	$(OBJDIR)/CNPKReader.o \
	$(OBJDIR)/CSceneNodeAnimatorDelete.o \
	$(OBJDIR)/CTarReader.o \
	$(OBJDIR)/CSkyDomeSceneNode.o \
	$(OBJDIR)/CLimitReadFile.o \
	$(OBJDIR)/CImageLoaderPPM.o \
	$(OBJDIR)/CSceneNodeAnimatorRotation.o \
	$(OBJDIR)/CImageWriterPPM.o \
	$(OBJDIR)/CNullDriver.o \
	$(OBJDIR)/CGUISpriteBank.o \
	$(OBJDIR)/CDummyTransformationSceneNode.o \
	$(OBJDIR)/CGUIMeshViewer.o \
	$(OBJDIR)/CSoftwareTexture.o \
	$(OBJDIR)/Irrlicht.o \
	$(OBJDIR)/CGUISpinBox.o \
	$(OBJDIR)/CDepthBuffer.o \
	$(OBJDIR)/CIrrMeshWriter.o \
	$(OBJDIR)/CImageWriterPNG.o \
	$(OBJDIR)/CSTLMeshFileLoader.o \
	$(OBJDIR)/CGUIWindow.o \
	$(OBJDIR)/CTRTextureBlend.o \
	$(OBJDIR)/CTRStencilShadow.o \
	$(OBJDIR)/CIrrDeviceWin32.o \
	$(OBJDIR)/CCSMLoader.o \
	$(OBJDIR)/CGUIListBox.o \
	$(OBJDIR)/CWriteFile.o \
	$(OBJDIR)/CImageWriterTGA.o \
	$(OBJDIR)/CShadowVolumeSceneNode.o \
	$(OBJDIR)/COgreMeshFileLoader.o \
	$(OBJDIR)/CCubeSceneNode.o \
	$(OBJDIR)/CImageLoaderBMP.o \
	$(OBJDIR)/CParticleSphereEmitter.o \
	$(OBJDIR)/CImageLoaderPCX.o \
	$(OBJDIR)/CImageLoaderJPG.o \
	$(OBJDIR)/CLightSceneNode.o \
	$(OBJDIR)/CIrrMeshFileLoader.o \
	$(OBJDIR)/irrXML.o \
	$(OBJDIR)/CTRTextureLightMap2_Add.o \
	$(OBJDIR)/CTRTextureGouraud.o \
	$(OBJDIR)/CParticleSystemSceneNode.o \
	$(OBJDIR)/CParticleBoxEmitter.o \
	$(OBJDIR)/CMS3DMeshFileLoader.o \
	$(OBJDIR)/CB3DMeshFileLoader.o \
	$(OBJDIR)/CSceneNodeAnimatorFlyCircle.o \
	$(OBJDIR)/CIrrDeviceConsole.o \
	$(OBJDIR)/CBSPMeshFileLoader.o \
	$(OBJDIR)/CTRGouraudAlpha2.o \
	$(OBJDIR)/CVideoModeList.o \
	$(OBJDIR)/CWADReader.o \
	$(OBJDIR)/COpenGLCgMaterialRenderer.o \
	$(OBJDIR)/CMD3MeshFileLoader.o \
	$(OBJDIR)/CImageWriterPCX.o \
	$(OBJDIR)/CDMFLoader.o \
	$(OBJDIR)/COBJMeshFileLoader.o \
	$(OBJDIR)/CTRGouraud.o \
	$(OBJDIR)/CGUIImage.o \
	$(OBJDIR)/CSTLMeshWriter.o \
	$(OBJDIR)/CParticleFadeOutAffector.o \
	$(OBJDIR)/CGUIImageList.o \
	$(OBJDIR)/CAnimatedMeshSceneNode.o \
	$(OBJDIR)/CD3D8NormalMapRenderer.o \
	$(OBJDIR)/CTRTextureLightMapGouraud2_M4.o \
	$(OBJDIR)/CCgMaterialRenderer.o \
	$(OBJDIR)/os.o \
	$(OBJDIR)/CPLYMeshWriter.o \
	$(OBJDIR)/CD3D9Texture.o \
	$(OBJDIR)/CSceneNodeAnimatorFollowSpline.o \
	$(OBJDIR)/CTRTextureGouraudAlphaNoZ.o \
	$(OBJDIR)/CD3D8Driver.o \
	$(OBJDIR)/CGUITable.o \
	$(OBJDIR)/CXMLReader.o \
	$(OBJDIR)/CIrrDeviceSDL.o \
	$(OBJDIR)/CGeometryCreator.o \
	$(OBJDIR)/CD3D9ShaderMaterialRenderer.o \
	$(OBJDIR)/CFPSCounter.o \
	$(OBJDIR)/CColladaMeshWriter.o \
	$(OBJDIR)/CBurningShader_Raster_Reference.o \
	$(OBJDIR)/CSkyBoxSceneNode.o \
	$(OBJDIR)/CTRTextureFlatWire.o \
	$(OBJDIR)/CMD2MeshFileLoader.o \
	$(OBJDIR)/CGUIFileOpenDialog.o \
	$(OBJDIR)/CSceneManager.o \
	$(OBJDIR)/CLogger.o \
	$(OBJDIR)/CMeshSceneNode.o \
	$(OBJDIR)/CImageWriterBMP.o \
	$(OBJDIR)/COpenGLShaderMaterialRenderer.o \
	$(OBJDIR)/CSkinnedMesh.o \
	$(OBJDIR)/CTRTextureGouraudAddNoZ2.o \
	$(OBJDIR)/CSceneNodeAnimatorCameraFPS.o \
	$(OBJDIR)/CQuake3ShaderSceneNode.o \
	$(OBJDIR)/CTRTextureWire2.o \
	$(OBJDIR)/CTerrainTriangleSelector.o \
	$(OBJDIR)/CMeshCache.o \
	$(OBJDIR)/COctreeSceneNode.o \
	$(OBJDIR)/CImage.o \
	$(OBJDIR)/CSceneLoaderIrr.o \
	$(OBJDIR)/CAttributes.o \
	$(OBJDIR)/CMountPointReader.o \
	$(OBJDIR)/COSOperator.o \
	$(OBJDIR)/COpenGLExtensionHandler.o \
	$(OBJDIR)/CXMLWriter.o \
	$(OBJDIR)/CSMFMeshFileLoader.o \
	$(OBJDIR)/CGUITabControl.o \
	$(OBJDIR)/CTRTextureDetailMap2.o \
	$(OBJDIR)/CTRTextureGouraudNoZ.o \
	$(OBJDIR)/CImageLoaderDDS.o \
	$(OBJDIR)/CSceneNodeAnimatorTexture.o \
	$(OBJDIR)/CIrrDeviceLinux.o \
	$(OBJDIR)/CGUITreeView.o \
	$(OBJDIR)/IBurningShader.o \
	$(OBJDIR)/CGUIMenu.o \
	$(OBJDIR)/CImageLoaderPSD.o \
	$(OBJDIR)/CColladaFileLoader.o \
	$(OBJDIR)/CD3D8ParallaxMapRenderer.o \
	$(OBJDIR)/CQ3LevelMesh.o \
	$(OBJDIR)/CGUIContextMenu.o \
	$(OBJDIR)/CDefaultSceneNodeFactory.o \
	$(OBJDIR)/CVolumeLightSceneNode.o \
	$(OBJDIR)/CSceneCollisionManager.o \
	$(OBJDIR)/CSceneNodeAnimatorFlyStraight.o \
	$(OBJDIR)/CEmptySceneNode.o \
	$(OBJDIR)/COCTLoader.o \
	$(OBJDIR)/CMemoryFile.o \
	$(OBJDIR)/CFileSystem.o \
	$(OBJDIR)/CMY3DMeshFileLoader.o \
	$(OBJDIR)/CTRTextureGouraudAlpha.o \
	$(OBJDIR)/CImageWriterPSD.o \
	$(OBJDIR)/CGUIToolBar.o \
	$(OBJDIR)/CImageLoaderTGA.o \
	$(OBJDIR)/CGUIStaticText.o \
	$(OBJDIR)/CZBuffer.o \
	$(OBJDIR)/CLWOMeshFileLoader.o \
	$(OBJDIR)/CTRTextureLightMap2_M4.o \
	$(OBJDIR)/CSoftwareDriver2.o \
	$(OBJDIR)/CBoneSceneNode.o \
	$(OBJDIR)/CTRNormalMap.o \
	$(OBJDIR)/COctreeTriangleSelector.o \
	$(OBJDIR)/CFileList.o \
	$(OBJDIR)/CD3D9Driver.o \
	$(OBJDIR)/CTRGouraud2.o \
	$(OBJDIR)/CTRTextureGouraudVertexAlpha2.o \
	$(OBJDIR)/COpenGLSLMaterialRenderer.o \
	$(OBJDIR)/CGUIScrollBar.o \
	$(OBJDIR)/CD3D9NormalMapRenderer.o \
	$(OBJDIR)/CSceneNodeAnimatorCollisionResponse.o \
	$(OBJDIR)/CGUICheckBox.o \
	$(OBJDIR)/CParticleAnimatedMeshSceneNodeEmitter.o \
	$(OBJDIR)/CSceneNodeAnimatorCameraMaya.o \
	$(OBJDIR)/CGUIModalScreen.o \
	$(OBJDIR)/CDefaultGUIElementFactory.o \
	$(OBJDIR)/CTRTextureGouraudAdd2.o \
	$(OBJDIR)/COpenGLTexture.o \
	$(OBJDIR)/CGUIFont.o \
	$(OBJDIR)/C3DSMeshFileLoader.o \
	$(OBJDIR)/CTRTextureGouraudWire.o \
	$(OBJDIR)/CSoftwareDriver.o \
	$(OBJDIR)/hmac.o \
	$(OBJDIR)/pwd2key.o \
	$(OBJDIR)/sha2.o \
	$(OBJDIR)/sha1.o \
	$(OBJDIR)/aestab.o \
	$(OBJDIR)/fileenc.o \
	$(OBJDIR)/prng.o \
	$(OBJDIR)/aeskey.o \
	$(OBJDIR)/aescrypt.o \
	$(OBJDIR)/wrtarga.o \
	$(OBJDIR)/wrgif.o \
	$(OBJDIR)/jcinit.o \
	$(OBJDIR)/jdatadst.o \
	$(OBJDIR)/jaricom.o \
	$(OBJDIR)/rdrle.o \
	$(OBJDIR)/ansi2knr.o \
	$(OBJDIR)/jccoefct.o \
	$(OBJDIR)/jidctflt.o \
	$(OBJDIR)/jcparam.o \
	$(OBJDIR)/jfdctint.o \
	$(OBJDIR)/jdarith.o \
	$(OBJDIR)/djpeg.o \
	$(OBJDIR)/transupp.o \
	$(OBJDIR)/rdtarga.o \
	$(OBJDIR)/jdmaster.o \
	$(OBJDIR)/rdcolmap.o \
	$(OBJDIR)/jcprepct.o \
	$(OBJDIR)/jdcoefct.o \
	$(OBJDIR)/jddctmgr.o \
	$(OBJDIR)/jdhuff.o \
	$(OBJDIR)/jutils.o \
	$(OBJDIR)/jcdctmgr.o \
	$(OBJDIR)/wrbmp.o \
	$(OBJDIR)/jdatasrc.o \
	$(OBJDIR)/jidctint.o \
	$(OBJDIR)/jdinput.o \
	$(OBJDIR)/jerror.o \
	$(OBJDIR)/jfdctflt.o \
	$(OBJDIR)/jmemname.o \
	$(OBJDIR)/jmemnobs.o \
	$(OBJDIR)/jccolor.o \
	$(OBJDIR)/wrppm.o \
	$(OBJDIR)/jdmerge.o \
	$(OBJDIR)/jcomapi.o \
	$(OBJDIR)/jdpostct.o \
	$(OBJDIR)/cjpeg.o \
	$(OBJDIR)/jquant2.o \
	$(OBJDIR)/jcmarker.o \
	$(OBJDIR)/jpegtran.o \
	$(OBJDIR)/jcapimin.o \
	$(OBJDIR)/jidctfst.o \
	$(OBJDIR)/jcarith.o \
	$(OBJDIR)/jchuff.o \
	$(OBJDIR)/jmemansi.o \
	$(OBJDIR)/jdcolor.o \
	$(OBJDIR)/jdapistd.o \
	$(OBJDIR)/ckconfig.o \
	$(OBJDIR)/jdtrans.o \
	$(OBJDIR)/jmemmgr.o \
	$(OBJDIR)/jdmarker.o \
	$(OBJDIR)/jfdctfst.o \
	$(OBJDIR)/wrrle.o \
	$(OBJDIR)/jcsample.o \
	$(OBJDIR)/jcmaster.o \
	$(OBJDIR)/jdsample.o \
	$(OBJDIR)/jcapistd.o \
	$(OBJDIR)/jctrans.o \
	$(OBJDIR)/jquant1.o \
	$(OBJDIR)/jdmainct.o \
	$(OBJDIR)/rdppm.o \
	$(OBJDIR)/jcmainct.o \
	$(OBJDIR)/rdgif.o \
	$(OBJDIR)/rdbmp.o \
	$(OBJDIR)/rdswitch.o \
	$(OBJDIR)/jdapimin.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking Irrlicht
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Irrlicht
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	-$(SILENT) cp $< $(OBJDIR)
else
	$(SILENT) xcopy /D /Y /Q "$(subst /,\,$<)" "$(subst /,\,$(OBJDIR))" 1>nul
endif
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
endif

$(OBJDIR)/CSoftwareTexture2.o: ../../external/irrlicht/source/Irrlicht/CSoftwareTexture2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CColorConverter.o: ../../external/irrlicht/source/Irrlicht/CColorConverter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CIrrDeviceStub.o: ../../external/irrlicht/source/Irrlicht/CIrrDeviceStub.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D9ParallaxMapRenderer.o: ../../external/irrlicht/source/Irrlicht/CD3D9ParallaxMapRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CIrrDeviceFB.o: ../../external/irrlicht/source/Irrlicht/CIrrDeviceFB.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleAttractionAffector.o: ../../external/irrlicht/source/Irrlicht/CParticleAttractionAffector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleRingEmitter.o: ../../external/irrlicht/source/Irrlicht/CParticleRingEmitter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageWriterJPG.o: ../../external/irrlicht/source/Irrlicht/CImageWriterJPG.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CAnimatedMeshMD3.o: ../../external/irrlicht/source/Irrlicht/CAnimatedMeshMD3.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageLoaderWAL.o: ../../external/irrlicht/source/Irrlicht/CImageLoaderWAL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTextSceneNode.o: ../../external/irrlicht/source/Irrlicht/CTextSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticlePointEmitter.o: ../../external/irrlicht/source/Irrlicht/CParticlePointEmitter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CIrrDeviceWinCE.o: ../../external/irrlicht/source/Irrlicht/CIrrDeviceWinCE.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COpenGLParallaxMapRenderer.o: ../../external/irrlicht/source/Irrlicht/COpenGLParallaxMapRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIColorSelectDialog.o: ../../external/irrlicht/source/Irrlicht/CGUIColorSelectDialog.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CPakReader.o: ../../external/irrlicht/source/Irrlicht/CPakReader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleMeshEmitter.o: ../../external/irrlicht/source/Irrlicht/CParticleMeshEmitter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CZipReader.o: ../../external/irrlicht/source/Irrlicht/CZipReader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CAnimatedMeshHalfLife.o: ../../external/irrlicht/source/Irrlicht/CAnimatedMeshHalfLife.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageLoaderPNG.o: ../../external/irrlicht/source/Irrlicht/CImageLoaderPNG.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIEditBox.o: ../../external/irrlicht/source/Irrlicht/CGUIEditBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleRotationAffector.o: ../../external/irrlicht/source/Irrlicht/CParticleRotationAffector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CReadFile.o: ../../external/irrlicht/source/Irrlicht/CReadFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIButton.o: ../../external/irrlicht/source/Irrlicht/CGUIButton.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleCylinderEmitter.o: ../../external/irrlicht/source/Irrlicht/CParticleCylinderEmitter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CBillboardSceneNode.o: ../../external/irrlicht/source/Irrlicht/CBillboardSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D8ShaderMaterialRenderer.o: ../../external/irrlicht/source/Irrlicht/CD3D8ShaderMaterialRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CXMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CXMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CMeshManipulator.o: ../../external/irrlicht/source/Irrlicht/CMeshManipulator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CAnimatedMeshMD2.o: ../../external/irrlicht/source/Irrlicht/CAnimatedMeshMD2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRGouraudAlphaNoZ2.o: ../../external/irrlicht/source/Irrlicht/CTRGouraudAlphaNoZ2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureLightMap2_M2.o: ../../external/irrlicht/source/Irrlicht/CTRTextureLightMap2_M2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D9CgMaterialRenderer.o: ../../external/irrlicht/source/Irrlicht/CD3D9CgMaterialRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COpenGLNormalMapRenderer.o: ../../external/irrlicht/source/Irrlicht/COpenGLNormalMapRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureFlat.o: ../../external/irrlicht/source/Irrlicht/CTRTextureFlat.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageLoaderRGB.o: ../../external/irrlicht/source/Irrlicht/CImageLoaderRGB.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRGouraudWire.o: ../../external/irrlicht/source/Irrlicht/CTRGouraudWire.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTriangleSelector.o: ../../external/irrlicht/source/Irrlicht/CTriangleSelector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CLMTSMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CLMTSMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureLightMap2_M1.o: ../../external/irrlicht/source/Irrlicht/CTRTextureLightMap2_M1.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleScaleAffector.o: ../../external/irrlicht/source/Irrlicht/CParticleScaleAffector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTriangleBBSelector.o: ../../external/irrlicht/source/Irrlicht/CTriangleBBSelector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraudAdd.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraudAdd.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CPLYMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CPLYMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COpenGLDriver.o: ../../external/irrlicht/source/Irrlicht/COpenGLDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIInOutFader.o: ../../external/irrlicht/source/Irrlicht/CGUIInOutFader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CWaterSurfaceSceneNode.o: ../../external/irrlicht/source/Irrlicht/CWaterSurfaceSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraudNoZ2.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraudNoZ2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D9HLSLMaterialRenderer.o: ../../external/irrlicht/source/Irrlicht/CD3D9HLSLMaterialRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CMetaTriangleSelector.o: ../../external/irrlicht/source/Irrlicht/CMetaTriangleSelector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIEnvironment.o: ../../external/irrlicht/source/Irrlicht/CGUIEnvironment.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraud2.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraud2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTerrainSceneNode.o: ../../external/irrlicht/source/Irrlicht/CTerrainSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIComboBox.o: ../../external/irrlicht/source/Irrlicht/CGUIComboBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleGravityAffector.o: ../../external/irrlicht/source/Irrlicht/CParticleGravityAffector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COBJMeshWriter.o: ../../external/irrlicht/source/Irrlicht/COBJMeshWriter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CDefaultSceneNodeAnimatorFactory.o: ../../external/irrlicht/source/Irrlicht/CDefaultSceneNodeAnimatorFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D8Texture.o: ../../external/irrlicht/source/Irrlicht/CD3D8Texture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CCameraSceneNode.o: ../../external/irrlicht/source/Irrlicht/CCameraSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRFlatWire.o: ../../external/irrlicht/source/Irrlicht/CTRFlatWire.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUISkin.o: ../../external/irrlicht/source/Irrlicht/CGUISkin.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSphereSceneNode.o: ../../external/irrlicht/source/Irrlicht/CSphereSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIMessageBox.o: ../../external/irrlicht/source/Irrlicht/CGUIMessageBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRFlat.o: ../../external/irrlicht/source/Irrlicht/CTRFlat.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CNPKReader.o: ../../external/irrlicht/source/Irrlicht/CNPKReader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneNodeAnimatorDelete.o: ../../external/irrlicht/source/Irrlicht/CSceneNodeAnimatorDelete.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTarReader.o: ../../external/irrlicht/source/Irrlicht/CTarReader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSkyDomeSceneNode.o: ../../external/irrlicht/source/Irrlicht/CSkyDomeSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CLimitReadFile.o: ../../external/irrlicht/source/Irrlicht/CLimitReadFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageLoaderPPM.o: ../../external/irrlicht/source/Irrlicht/CImageLoaderPPM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneNodeAnimatorRotation.o: ../../external/irrlicht/source/Irrlicht/CSceneNodeAnimatorRotation.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageWriterPPM.o: ../../external/irrlicht/source/Irrlicht/CImageWriterPPM.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CNullDriver.o: ../../external/irrlicht/source/Irrlicht/CNullDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUISpriteBank.o: ../../external/irrlicht/source/Irrlicht/CGUISpriteBank.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CDummyTransformationSceneNode.o: ../../external/irrlicht/source/Irrlicht/CDummyTransformationSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIMeshViewer.o: ../../external/irrlicht/source/Irrlicht/CGUIMeshViewer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSoftwareTexture.o: ../../external/irrlicht/source/Irrlicht/CSoftwareTexture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Irrlicht.o: ../../external/irrlicht/source/Irrlicht/Irrlicht.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUISpinBox.o: ../../external/irrlicht/source/Irrlicht/CGUISpinBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CDepthBuffer.o: ../../external/irrlicht/source/Irrlicht/CDepthBuffer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CIrrMeshWriter.o: ../../external/irrlicht/source/Irrlicht/CIrrMeshWriter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageWriterPNG.o: ../../external/irrlicht/source/Irrlicht/CImageWriterPNG.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSTLMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CSTLMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIWindow.o: ../../external/irrlicht/source/Irrlicht/CGUIWindow.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureBlend.o: ../../external/irrlicht/source/Irrlicht/CTRTextureBlend.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRStencilShadow.o: ../../external/irrlicht/source/Irrlicht/CTRStencilShadow.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CIrrDeviceWin32.o: ../../external/irrlicht/source/Irrlicht/CIrrDeviceWin32.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CCSMLoader.o: ../../external/irrlicht/source/Irrlicht/CCSMLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIListBox.o: ../../external/irrlicht/source/Irrlicht/CGUIListBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CWriteFile.o: ../../external/irrlicht/source/Irrlicht/CWriteFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageWriterTGA.o: ../../external/irrlicht/source/Irrlicht/CImageWriterTGA.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CShadowVolumeSceneNode.o: ../../external/irrlicht/source/Irrlicht/CShadowVolumeSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COgreMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/COgreMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CCubeSceneNode.o: ../../external/irrlicht/source/Irrlicht/CCubeSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageLoaderBMP.o: ../../external/irrlicht/source/Irrlicht/CImageLoaderBMP.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleSphereEmitter.o: ../../external/irrlicht/source/Irrlicht/CParticleSphereEmitter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageLoaderPCX.o: ../../external/irrlicht/source/Irrlicht/CImageLoaderPCX.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageLoaderJPG.o: ../../external/irrlicht/source/Irrlicht/CImageLoaderJPG.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CLightSceneNode.o: ../../external/irrlicht/source/Irrlicht/CLightSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CIrrMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CIrrMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/irrXML.o: ../../external/irrlicht/source/Irrlicht/irrXML.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureLightMap2_Add.o: ../../external/irrlicht/source/Irrlicht/CTRTextureLightMap2_Add.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraud.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraud.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleSystemSceneNode.o: ../../external/irrlicht/source/Irrlicht/CParticleSystemSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleBoxEmitter.o: ../../external/irrlicht/source/Irrlicht/CParticleBoxEmitter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CMS3DMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CMS3DMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CB3DMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CB3DMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneNodeAnimatorFlyCircle.o: ../../external/irrlicht/source/Irrlicht/CSceneNodeAnimatorFlyCircle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CIrrDeviceConsole.o: ../../external/irrlicht/source/Irrlicht/CIrrDeviceConsole.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CBSPMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CBSPMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRGouraudAlpha2.o: ../../external/irrlicht/source/Irrlicht/CTRGouraudAlpha2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CVideoModeList.o: ../../external/irrlicht/source/Irrlicht/CVideoModeList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CWADReader.o: ../../external/irrlicht/source/Irrlicht/CWADReader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COpenGLCgMaterialRenderer.o: ../../external/irrlicht/source/Irrlicht/COpenGLCgMaterialRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CMD3MeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CMD3MeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageWriterPCX.o: ../../external/irrlicht/source/Irrlicht/CImageWriterPCX.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CDMFLoader.o: ../../external/irrlicht/source/Irrlicht/CDMFLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COBJMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/COBJMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRGouraud.o: ../../external/irrlicht/source/Irrlicht/CTRGouraud.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIImage.o: ../../external/irrlicht/source/Irrlicht/CGUIImage.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSTLMeshWriter.o: ../../external/irrlicht/source/Irrlicht/CSTLMeshWriter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleFadeOutAffector.o: ../../external/irrlicht/source/Irrlicht/CParticleFadeOutAffector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIImageList.o: ../../external/irrlicht/source/Irrlicht/CGUIImageList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CAnimatedMeshSceneNode.o: ../../external/irrlicht/source/Irrlicht/CAnimatedMeshSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D8NormalMapRenderer.o: ../../external/irrlicht/source/Irrlicht/CD3D8NormalMapRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureLightMapGouraud2_M4.o: ../../external/irrlicht/source/Irrlicht/CTRTextureLightMapGouraud2_M4.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CCgMaterialRenderer.o: ../../external/irrlicht/source/Irrlicht/CCgMaterialRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/os.o: ../../external/irrlicht/source/Irrlicht/os.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CPLYMeshWriter.o: ../../external/irrlicht/source/Irrlicht/CPLYMeshWriter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D9Texture.o: ../../external/irrlicht/source/Irrlicht/CD3D9Texture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneNodeAnimatorFollowSpline.o: ../../external/irrlicht/source/Irrlicht/CSceneNodeAnimatorFollowSpline.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraudAlphaNoZ.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraudAlphaNoZ.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D8Driver.o: ../../external/irrlicht/source/Irrlicht/CD3D8Driver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUITable.o: ../../external/irrlicht/source/Irrlicht/CGUITable.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CXMLReader.o: ../../external/irrlicht/source/Irrlicht/CXMLReader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CIrrDeviceSDL.o: ../../external/irrlicht/source/Irrlicht/CIrrDeviceSDL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGeometryCreator.o: ../../external/irrlicht/source/Irrlicht/CGeometryCreator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D9ShaderMaterialRenderer.o: ../../external/irrlicht/source/Irrlicht/CD3D9ShaderMaterialRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CFPSCounter.o: ../../external/irrlicht/source/Irrlicht/CFPSCounter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CColladaMeshWriter.o: ../../external/irrlicht/source/Irrlicht/CColladaMeshWriter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CBurningShader_Raster_Reference.o: ../../external/irrlicht/source/Irrlicht/CBurningShader_Raster_Reference.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSkyBoxSceneNode.o: ../../external/irrlicht/source/Irrlicht/CSkyBoxSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureFlatWire.o: ../../external/irrlicht/source/Irrlicht/CTRTextureFlatWire.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CMD2MeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CMD2MeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIFileOpenDialog.o: ../../external/irrlicht/source/Irrlicht/CGUIFileOpenDialog.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneManager.o: ../../external/irrlicht/source/Irrlicht/CSceneManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CLogger.o: ../../external/irrlicht/source/Irrlicht/CLogger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CMeshSceneNode.o: ../../external/irrlicht/source/Irrlicht/CMeshSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageWriterBMP.o: ../../external/irrlicht/source/Irrlicht/CImageWriterBMP.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COpenGLShaderMaterialRenderer.o: ../../external/irrlicht/source/Irrlicht/COpenGLShaderMaterialRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSkinnedMesh.o: ../../external/irrlicht/source/Irrlicht/CSkinnedMesh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraudAddNoZ2.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraudAddNoZ2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneNodeAnimatorCameraFPS.o: ../../external/irrlicht/source/Irrlicht/CSceneNodeAnimatorCameraFPS.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CQuake3ShaderSceneNode.o: ../../external/irrlicht/source/Irrlicht/CQuake3ShaderSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureWire2.o: ../../external/irrlicht/source/Irrlicht/CTRTextureWire2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTerrainTriangleSelector.o: ../../external/irrlicht/source/Irrlicht/CTerrainTriangleSelector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CMeshCache.o: ../../external/irrlicht/source/Irrlicht/CMeshCache.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COctreeSceneNode.o: ../../external/irrlicht/source/Irrlicht/COctreeSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImage.o: ../../external/irrlicht/source/Irrlicht/CImage.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneLoaderIrr.o: ../../external/irrlicht/source/Irrlicht/CSceneLoaderIrr.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CAttributes.o: ../../external/irrlicht/source/Irrlicht/CAttributes.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CMountPointReader.o: ../../external/irrlicht/source/Irrlicht/CMountPointReader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COSOperator.o: ../../external/irrlicht/source/Irrlicht/COSOperator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COpenGLExtensionHandler.o: ../../external/irrlicht/source/Irrlicht/COpenGLExtensionHandler.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CXMLWriter.o: ../../external/irrlicht/source/Irrlicht/CXMLWriter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSMFMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CSMFMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUITabControl.o: ../../external/irrlicht/source/Irrlicht/CGUITabControl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureDetailMap2.o: ../../external/irrlicht/source/Irrlicht/CTRTextureDetailMap2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraudNoZ.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraudNoZ.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageLoaderDDS.o: ../../external/irrlicht/source/Irrlicht/CImageLoaderDDS.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneNodeAnimatorTexture.o: ../../external/irrlicht/source/Irrlicht/CSceneNodeAnimatorTexture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CIrrDeviceLinux.o: ../../external/irrlicht/source/Irrlicht/CIrrDeviceLinux.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUITreeView.o: ../../external/irrlicht/source/Irrlicht/CGUITreeView.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/IBurningShader.o: ../../external/irrlicht/source/Irrlicht/IBurningShader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIMenu.o: ../../external/irrlicht/source/Irrlicht/CGUIMenu.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageLoaderPSD.o: ../../external/irrlicht/source/Irrlicht/CImageLoaderPSD.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CColladaFileLoader.o: ../../external/irrlicht/source/Irrlicht/CColladaFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D8ParallaxMapRenderer.o: ../../external/irrlicht/source/Irrlicht/CD3D8ParallaxMapRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CQ3LevelMesh.o: ../../external/irrlicht/source/Irrlicht/CQ3LevelMesh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIContextMenu.o: ../../external/irrlicht/source/Irrlicht/CGUIContextMenu.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CDefaultSceneNodeFactory.o: ../../external/irrlicht/source/Irrlicht/CDefaultSceneNodeFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CVolumeLightSceneNode.o: ../../external/irrlicht/source/Irrlicht/CVolumeLightSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneCollisionManager.o: ../../external/irrlicht/source/Irrlicht/CSceneCollisionManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneNodeAnimatorFlyStraight.o: ../../external/irrlicht/source/Irrlicht/CSceneNodeAnimatorFlyStraight.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CEmptySceneNode.o: ../../external/irrlicht/source/Irrlicht/CEmptySceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COCTLoader.o: ../../external/irrlicht/source/Irrlicht/COCTLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CMemoryFile.o: ../../external/irrlicht/source/Irrlicht/CMemoryFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CFileSystem.o: ../../external/irrlicht/source/Irrlicht/CFileSystem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CMY3DMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CMY3DMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraudAlpha.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraudAlpha.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageWriterPSD.o: ../../external/irrlicht/source/Irrlicht/CImageWriterPSD.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIToolBar.o: ../../external/irrlicht/source/Irrlicht/CGUIToolBar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CImageLoaderTGA.o: ../../external/irrlicht/source/Irrlicht/CImageLoaderTGA.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIStaticText.o: ../../external/irrlicht/source/Irrlicht/CGUIStaticText.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CZBuffer.o: ../../external/irrlicht/source/Irrlicht/CZBuffer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CLWOMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/CLWOMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureLightMap2_M4.o: ../../external/irrlicht/source/Irrlicht/CTRTextureLightMap2_M4.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSoftwareDriver2.o: ../../external/irrlicht/source/Irrlicht/CSoftwareDriver2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CBoneSceneNode.o: ../../external/irrlicht/source/Irrlicht/CBoneSceneNode.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRNormalMap.o: ../../external/irrlicht/source/Irrlicht/CTRNormalMap.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COctreeTriangleSelector.o: ../../external/irrlicht/source/Irrlicht/COctreeTriangleSelector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CFileList.o: ../../external/irrlicht/source/Irrlicht/CFileList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D9Driver.o: ../../external/irrlicht/source/Irrlicht/CD3D9Driver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRGouraud2.o: ../../external/irrlicht/source/Irrlicht/CTRGouraud2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraudVertexAlpha2.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraudVertexAlpha2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COpenGLSLMaterialRenderer.o: ../../external/irrlicht/source/Irrlicht/COpenGLSLMaterialRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIScrollBar.o: ../../external/irrlicht/source/Irrlicht/CGUIScrollBar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CD3D9NormalMapRenderer.o: ../../external/irrlicht/source/Irrlicht/CD3D9NormalMapRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneNodeAnimatorCollisionResponse.o: ../../external/irrlicht/source/Irrlicht/CSceneNodeAnimatorCollisionResponse.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUICheckBox.o: ../../external/irrlicht/source/Irrlicht/CGUICheckBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CParticleAnimatedMeshSceneNodeEmitter.o: ../../external/irrlicht/source/Irrlicht/CParticleAnimatedMeshSceneNodeEmitter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSceneNodeAnimatorCameraMaya.o: ../../external/irrlicht/source/Irrlicht/CSceneNodeAnimatorCameraMaya.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIModalScreen.o: ../../external/irrlicht/source/Irrlicht/CGUIModalScreen.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CDefaultGUIElementFactory.o: ../../external/irrlicht/source/Irrlicht/CDefaultGUIElementFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraudAdd2.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraudAdd2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/COpenGLTexture.o: ../../external/irrlicht/source/Irrlicht/COpenGLTexture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CGUIFont.o: ../../external/irrlicht/source/Irrlicht/CGUIFont.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/C3DSMeshFileLoader.o: ../../external/irrlicht/source/Irrlicht/C3DSMeshFileLoader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CTRTextureGouraudWire.o: ../../external/irrlicht/source/Irrlicht/CTRTextureGouraudWire.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CSoftwareDriver.o: ../../external/irrlicht/source/Irrlicht/CSoftwareDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/hmac.o: ../../external/irrlicht/source/Irrlicht/aesGladman/hmac.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/pwd2key.o: ../../external/irrlicht/source/Irrlicht/aesGladman/pwd2key.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/sha2.o: ../../external/irrlicht/source/Irrlicht/aesGladman/sha2.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/sha1.o: ../../external/irrlicht/source/Irrlicht/aesGladman/sha1.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/aestab.o: ../../external/irrlicht/source/Irrlicht/aesGladman/aestab.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/fileenc.o: ../../external/irrlicht/source/Irrlicht/aesGladman/fileenc.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/prng.o: ../../external/irrlicht/source/Irrlicht/aesGladman/prng.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/aeskey.o: ../../external/irrlicht/source/Irrlicht/aesGladman/aeskey.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/aescrypt.o: ../../external/irrlicht/source/Irrlicht/aesGladman/aescrypt.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/wrtarga.o: ../../external/irrlicht/source/Irrlicht/jpeglib/wrtarga.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/wrgif.o: ../../external/irrlicht/source/Irrlicht/jpeglib/wrgif.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcinit.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcinit.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdatadst.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdatadst.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jaricom.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jaricom.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/rdrle.o: ../../external/irrlicht/source/Irrlicht/jpeglib/rdrle.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ansi2knr.o: ../../external/irrlicht/source/Irrlicht/jpeglib/ansi2knr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jccoefct.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jccoefct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jidctflt.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jidctflt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcparam.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcparam.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jfdctint.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jfdctint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdarith.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdarith.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/djpeg.o: ../../external/irrlicht/source/Irrlicht/jpeglib/djpeg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/transupp.o: ../../external/irrlicht/source/Irrlicht/jpeglib/transupp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/rdtarga.o: ../../external/irrlicht/source/Irrlicht/jpeglib/rdtarga.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdmaster.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdmaster.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/rdcolmap.o: ../../external/irrlicht/source/Irrlicht/jpeglib/rdcolmap.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcprepct.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcprepct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdcoefct.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdcoefct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jddctmgr.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jddctmgr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdhuff.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdhuff.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jutils.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jutils.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcdctmgr.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcdctmgr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/wrbmp.o: ../../external/irrlicht/source/Irrlicht/jpeglib/wrbmp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdatasrc.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdatasrc.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jidctint.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jidctint.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdinput.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdinput.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jerror.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jerror.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jfdctflt.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jfdctflt.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jmemname.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jmemname.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jmemnobs.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jmemnobs.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jccolor.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jccolor.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/wrppm.o: ../../external/irrlicht/source/Irrlicht/jpeglib/wrppm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdmerge.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdmerge.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcomapi.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcomapi.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdpostct.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdpostct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/cjpeg.o: ../../external/irrlicht/source/Irrlicht/jpeglib/cjpeg.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jquant2.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jquant2.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcmarker.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcmarker.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jpegtran.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jpegtran.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcapimin.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcapimin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jidctfst.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jidctfst.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcarith.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcarith.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jchuff.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jchuff.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jmemansi.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jmemansi.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdcolor.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdcolor.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdapistd.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdapistd.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ckconfig.o: ../../external/irrlicht/source/Irrlicht/jpeglib/ckconfig.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdtrans.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdtrans.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jmemmgr.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jmemmgr.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdmarker.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdmarker.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jfdctfst.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jfdctfst.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/wrrle.o: ../../external/irrlicht/source/Irrlicht/jpeglib/wrrle.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcsample.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcsample.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcmaster.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcmaster.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdsample.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdsample.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcapistd.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcapistd.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jctrans.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jctrans.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jquant1.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jquant1.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdmainct.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdmainct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/rdppm.o: ../../external/irrlicht/source/Irrlicht/jpeglib/rdppm.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jcmainct.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jcmainct.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/rdgif.o: ../../external/irrlicht/source/Irrlicht/jpeglib/rdgif.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/rdbmp.o: ../../external/irrlicht/source/Irrlicht/jpeglib/rdbmp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/rdswitch.o: ../../external/irrlicht/source/Irrlicht/jpeglib/rdswitch.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/jdapimin.o: ../../external/irrlicht/source/Irrlicht/jpeglib/jdapimin.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
